@ReservationSystem_HostAddress = http://localhost:5081

GET http://localhost:5081/api/reservations
Accept: application/json

###

POST http://localhost:5081/api/reservations
Content-Type: application/json
{
    "clientName": "Jack",
    "reservationDate": "2026-10-10",
    "reservationTime": "18:30",
    "PartySize": 4,
    "status": "pending"
}